name: my_dice_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^6.0.3
  provider: ^5.0.0
  geolocator: ^7.0.1
  google_fonts: ^2.0.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/dice1.png
    - images/dice2.png
    - images/dice3.png
    - images/dice4.png
    - images/dice5.png
    - images/dice6.png


#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/
#        - asset: fonts/
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/
#        - asset: fonts/
#          weight: 700
